### ISSUE TITLE
askama_axum doesn't seem to work? Trait not satisfied error

### ISSUE THREAD

**Issue by kinwolfqc** [djc/askama#570]
Hi, 
  One more problem I am facing trying to use askama_axum in the main branch.  The Derive macro seem to have a problem adding  into_response?  I get this error:

> error[E0277]: the trait bound `HelloTemplate: askama_axum::Template` is not satisfied
>    --> zata-web-app-ssr\src\bin\main.rs:107:10
>     |
> 107 | #[derive(Template)]
>     |          ^^^^^^^^ the trait `askama_axum::Template` is not implemented for `HelloTemplate`

> 11 | pub fn into_response<T: Template>(t: &T, ext: &str) -> Response<BoxBody> {
>    |                         ^^^^^^^^ required by this bound in `askama_axum::into_response`

Epurated version of my code
```
use askama::Template;
use axum::{
    extract,
    http::StatusCode,
    response::IntoResponse,
    routing::{get, get_service, post},
    AddExtensionLayer, Router,
};

#[tokio::main]
async fn main() {
    dotenv().ok();
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL is not set in .env file");
    let db_pool = PgPool::connect(&database_url).await.unwrap();
   // Set the RUST_LOG, if it hasn't been explicitly defined
    if std::env::var_os("RUST_LOG").is_none() {
        std::env::set_var("RUST_LOG", "zata_web_app=debug")
    }
    tracing_subscriber::fmt::init();

    let shared_state = Arc::new(AppState { db: db_pool });

    // build our application with some routes
    let app = Router::new()
        .route("/greet/:name", get(greet))       
        .nest(
            "/static",
            get_service(ServeDir::new(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/static"
            )))
        .handle_error(|error: std::io::Error| async move {
                (
                    StatusCode::INTERNAL_SERVER_ERROR,
                    format!("Unhandled internal error: {}", error),
                )
            }),
        )
        .layer(AddExtensionLayer::new(shared_state));

    // run it
    let addr = SocketAddr::from(([127, 0, 0, 1], 8080));
    tracing::debug!("listening on {}", addr);
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}


async fn greet(extract::Path(name): extract::Path<String>) -> impl IntoResponse {
    let template = HelloTemplate { name };
    HtmlTemplate(template)
}

#[derive(Template)]
#[template(path = "list.html")]
struct ListTutors {
    tutors: Vec<Tutor>,
}

#[derive(Template)]
#[template(path = "index.html")]
struct HelloTemplate {
    name: String,
}


```

I also tried to do a standalone version of the example in the repo and got the same error.

**Comment by djc** [comment]
@malyn would you happen to have any insights here?

**Comment by genusistimelord** [comment]
Try changing **-> impl IntoResponse** into **-> HelloTemplate**  and change **HtmlTemplate(template)** to **template** as askama_axum is already doing the above that the old method use to do but with all supported Derived Template type's.

**Comment by malyn** [comment]
@genusistimelord is correct on both accounts; those two changes should fix the problem. You should also be able to resolve this error with just the second change -- returning `template` instead of `HtmlTemplate(template)` -- but the Axum example in their repo recommends returning the actual template type (`HelloTemplate`) from the handler when possible.

**Comment by kinwolfqc** [comment]
Hi, 
  Thanks for the replies.  I had already tried changing the HTMLTemplate part in a subsequent iteration while trying to solve this, but the problem remained.  The compilation error isn't on the handler function but on the `#[derive(Template)]` part.

Here is a [screenshot](https://i.imgur.com/Nxzemh4.png)  showing that the highlighted error is really on the derive and it's message.  (along with the current handler code that indeed has the IntoResponse and HTMLTemplate replaced)

**Comment by malyn** [comment]
Thanks for the screenshot! Can you attach a copy of your Cargo.toml file as well, or at least the Axum- and Askama-related sections?

We recently pushed the Axum 0.4 update into the Askama repo and I am wondering if there is a mismatch in Axum versions... The signature of the `into_response` function changed between Axum 0.3 and Axum 0.4, so I could see a version mismatch causing this issue. (for example, if you are pulling the Askama repo prior to the Axum 0.4 upgrade, but using Axum at 0.4)

**Comment by kinwolfqc** [comment]
Sure, here it is:
```
[dependencies]
axum = "0.4"
#axum = { git = "https://github.com/tokio-rs/axum.git", branch = "main" }
<snip other crates for clarity>
#template engine
askama = { git = "https://github.com/djc/askama.git", branch = "main" , default-features = false, features = ["with-axum", "mime", "mime_guess"] }
askama_axum = { git = "https://github.com/djc/askama" }
```
Version of Axum installed for this project is 0.4.2 right now. I did a cargo update  earlier today to see if it would help.(no change)  I also tried with the main branch of Axum, same result.

**Comment by kinwolfqc** [comment]
Hmm, rust analyser is suggesting to do as a `use askama_axum::Template;` as a quick fix.  But if I do that(replacing  `use askama::Template` with `use askama_axum::Template` , the error is still there and the "new"  quick fix is to do a `use askama::Template`  Heh, it's going full circle :-P

**Comment by malyn** [comment]
Thanks for trying the `cargo update`; that was going to be my next question, if your `Cargo.lock` was referencing an older (pre-0.4) Askama commit, but `cargo update` fixes that, so that shouldn't be the issue. FWIW, I pinned my sample project's `Cargo.toml` to the Askama commit that added Axum 0.4 support (d77553d), but that shouldn't be necessary if you did the `cargo update`.

Anyway, let me see if I can repro this error on my end using your code. Your code and my sample are pretty similar, so this should "just work," but you know how that goes...

**Comment by kinwolfqc** [comment]
Here is the relevant parts of cargo.lock just to be sure,. Askama axum is v 0.10.0, not sure if it's right?

[[package]]
name = "askama"
version = "0.11.0"
source = "git+https://github.com/djc/askama#d77553d826f3c90999e0dd84f35cac3690c3d0ca"
dependencies = [
 "askama_derive",
 "askama_escape",
 "askama_shared",
 "mime",
 "mime_guess",
]

[[package]]
name = "askama_axum"
version = "0.10.0"
source = "git+https://github.com/djc/askama#d77553d826f3c90999e0dd84f35cac3690c3d0ca"
dependencies = [
 "askama",
 "axum-core",
 "http",
 "http-body",
]

[[package]]
name = "askama_derive"
version = "0.11.0"
source = "git+https://github.com/djc/askama#d77553d826f3c90999e0dd84f35cac3690c3d0ca"
dependencies = [
 "askama_shared",
 "proc-macro2",
 "syn",
]

[[package]]
name = "askama_escape"
version = "0.10.2"
source = "git+https://github.com/djc/askama#d77553d826f3c90999e0dd84f35cac3690c3d0ca"

[[package]]
name = "askama_shared"
version = "0.12.0"
source = "git+https://github.com/djc/askama#d77553d826f3c90999e0dd84f35cac3690c3d0ca"
dependencies = [
 "askama_escape",
 "nom",
 "proc-macro2",
 "quote",
 "syn",
]

[[package]]
name = "axum"
version = "0.4.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ae08f7a0b974a1b226b9a4bb07fcc865f25d7c7513cefc53603f84ab41e586fd"
dependencies = [
 "async-trait",
 "axum-core",
 "bitflags",
 "bytes",
 "futures-util",
 "http",
 "http-body",
 "hyper",
 "matchit",
 "mime",
 "percent-encoding",
 "pin-project-lite",
 "serde",
 "serde_json",
 "serde_urlencoded",
 "sync_wrapper",
 "tokio",
 "tokio-util",
 "tower",
 "tower-http 0.2.0",
 "tower-layer",
 "tower-service",
]

[[package]]
name = "axum-core"
version = "0.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1ca6c0b218388a7ed6a8d25e94f7dea5498daaa4fd8c711fb3ff166041b06fda"
dependencies = [
 "async-trait",
 "bytes",
 "futures-util",
 "http",
 "http-body",
 "mime",
]

[[package]]
name = "axum-debug"
version = "0.3.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "d773bd3fc42d1fe33f32a2fcdf5be07cbee0b5cbc325a1ccfe8b5ce36d56a4d8"
dependencies = [
 "proc-macro2",
 "quote",
 "syn",
]

**Comment by malyn** [comment]
I found the fix, but I am not exactly sure why it works. Basically, the `default-features = false` for `askama` in your Cargo.toml is somehow causing that error. Simplifying the `askama` dependency to the following seems to work fine:

```toml
askama = { git = "https://github.com/djc/askama.git", features = ["with-axum"] }
```

@djc might know why this is happening; perhaps something in the `template` macro is not getting compiled if you disable the default features. (although, FWIW, I tried adding back all of the default features manually and got the same error)

**Comment by kinwolfqc** [comment]
That was it indeed, it worked! No more error.

**Comment by djc** [comment]
That's pretty strange. Are you on edition 2021 and/or otherwise using Cargo's v2 resolver?

**Comment by genusistimelord** [comment]
I have been having issues with 2021's Cargo resolver. If his project is in a workspace with many projects he will need to also add resolver = "2" Otherwise it will not compile correctly.

**Comment by kinwolfqc** [comment]
The project was indeed created with cargo v1.56, so it set itself to 2021 by default.  I have 2 workspaces in the project, and the one workspace that use askama was set at 2021 initially, but I did set it back to 2018 in the cargo.toml of that workspace to see if it would help(it didn't).  But I didn't change it for the whole project, so not sure if it was enough to only change it in the workspace.

I did not know about cargo resolver at all, so it's not set anywhere.  I guess it's using the default.

**Comment by genusistimelord** [comment]
Ok, so if you have have a single workspace file that includes both of your projects then you must add a resolver = "2" to that workspace file. Otherwise the resolver will not work until you do this. It is a bug they have not fixed yet in the new 2021 cargo. It somehow wants to default to the old resolver if you don't do this.

in your individual projects you don't need to add resolver unless the edition is older than 2021 as it is auto dictated in the 2021 edition.

**Comment by malyn** [comment]
I think that the issue might be related to how feature flags work in `askama_derive`. As far as I can tell, the `axum` [feature](https://github.com/djc/askama/blob/95317478ccb9baab3d1797d693e4c33008434b50/askama_derive/Cargo.toml#L19) in `askama_derive` is what [enables](https://github.com/djc/askama/blob/95317478ccb9baab3d1797d693e4c33008434b50/askama_derive/src/lib.rs#L114) the [generation of the Axum template implementation](https://github.com/djc/askama/blob/95317478ccb9baab3d1797d693e4c33008434b50/askama_shared/src/generator.rs#L99-L101). My guess is that passing `default-features = false` to `askama` also disables all of the default features in `askama_derive`.

Explicitly adding `askama_derive` with the `axum` feature flag set fixes the original build issue:

```toml
askama = { git = "https://github.com/djc/askama.git", default-features = false, features = ["with-axum"] }
askama_derive = { git = "https://github.com/djc/askama.git", features = ["axum"] }
askama_axum = { git = "https://github.com/djc/askama.git" }
```

Is this the symptom caused by the new Cargo resolver?

**Comment by genusistimelord** [comment]
The only thing I see there that default would disable is the Config portion which is shared between derive and shared. I don't think that would cause it to not work correctly unless askama_axum needs config?  I do think this could be a issue of the resolver though.  They have the same issue over at wgpu where if you have a workspace with multiple projects even if the projects are set to 2021 the workspace must have the resolver added to it.  He did say he has 2 projects in his workspace.

**Comment by kinwolfqc** [comment]
> Ok, so if you have have a single workspace file that includes both of your projects then you must add a resolver = "2" to that workspace file

Got it, I modified it to
```
[package]
name = "zata"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["zata-web-service","zata-web-app-ssr"]
resolver = "2"
```

**Comment by genusistimelord** [comment]
yeah that should fix the issue then. Please let us know if it does.

**Comment by kinwolfqc** [comment]
Well, I completed the small changes required for axum 0.4 and askama_axum and everythnig compiles fine now.  All seems good. :)  I can resume developing the rest of the app, thanks for the help!

**Comment by djc** [comment]
Okay, going to close this. If anyone has changes to suggest to how the feature flags are set up, feel free to reopen or open a different issue/PR.
